### ISSUE TITLE
Carousel: incorrect switching between slides

### ISSUE THREAD

**Issue by NatkaDzoll** [coingaming/moon-design#2531]
## Describe the Bug

Carousel with large slide width, step={1}
On the first flip, the next slide is set in the center, but the subsequent flip scrolls almost to the end of the slides, skipping a few. 

## To Reproduce

Steps to reproduce the behavior

1. Go to '(https://bitcasino.io/bitcoin-breakdown)' - migration page to app router
2. Click on 'right arrow'
3. Click again on 'right arrow'

## Expected Behavior

A step-by-step transition is expected

## Possible Solution

Not obligatory, but suggest a fix/reason for the bug or ideas how to implement the addition or change.

## Your Environment

- Device: [Mac]
- OS: [iOS]
- Browser [chrome]
- Version [22]

**Comment by karl-kallavus** [comment]
@NatkaDzoll To address the scrolling issue with the carousel, our team plans to adjust the scrolling algorithm during the next sprint. 

This modification is aimed to make the carousel scroll amount equal to the width of one slide, regardless of the slide's current width, in order to provide a consistent user experience.

Sprint Details:

Goal: Enhance the functionality and user experience of the carousel.

### Tasks:

1) **Fix carousel scrolling issue:**
- [ ] Review existing scrolling code to identify the error.
- [ ] Revise and test the scrolling algorithm to ensure that it progresses by one slide at a time.

Also during the sprint following things will be fixed:

2) **Placeholder does not support JSX.Element:**
- [ ] Review and update the placeholder implementation to support JSX.Element.
- [ ] Improve carousel indicators (dots) default position inside Items:

3) **Refactor the carousel component to provide more flexibility in the positioning of indicators.**

4) **Resolve carousel bug that makes scroll visible:**
- [ ] Implement a fix for the scroll bar visibility in the carousel, ensuring necessary classes for the hide scrollbars utility.

5) **Optimize carousel indicators display when there are many items, especially on mobile:**
- [ ] Improve how indicators display to handle a high number of items better, ensuring appropriate visibility and functionality on mobile devices.
